hepsi: derle calistir

derle:
	gcc -I ./include/ -o ./lib/ArrayList.o -c ./src/ArrayList.c
	gcc -I ./include/ -o ./lib/DwarfPlanet.o -c ./src/DwarfPlanet.c
	gcc -I ./include/ -o ./lib/FileReader.o -c ./src/FileReader.c
	gcc -I ./include/ -o ./lib/GasGiantPlanet.o -c ./src/GasGiantPlanet.c
	gcc -I ./include/ -o ./lib/IceGiantPlanet.o -c ./src/IceGiantPlanet.c
	gcc -I ./include/ -o ./lib/ITimeListener.o -c ./src/ITimeListener.c
	gcc -I ./include/ -o ./lib/MyLocalTime.o -c ./src/MyLocalTime.c
	gcc -I ./include/ -o ./lib/Person.o -c ./src/Person.c
	gcc -I ./include/ -o ./lib/Planet.o -c ./src/Planet.c
	gcc -I ./include/ -o ./lib/Simulation.o -c ./src/Simulation.c
	gcc -I ./include/ -o ./lib/SpaceShip.o -c ./src/SpaceShip.c
	gcc -I ./include/ -o ./lib/StartSim_Facade.o -c ./src/StartSim_Facade.c
	gcc -I ./include/ -o ./lib/StringUtils.o -c ./src/StringUtils.c
	gcc -I ./include/ -o ./lib/TerrestrialPlanet.o -c ./src/TerrestrialPlanet.c
	gcc -I ./include/ -o ./lib/MyTime.o -c ./src/Time.c
	gcc -I ./include/ -o ./lib/PlanetLists.o -c ./src/PlanetLists.c
	gcc -I ./include/ -o ./bin/Simulasyon ./lib/*.o

calistir:
	./bin/Simulasyon
